function alpha_body = alphaP(phidot,phiddot,psidot,psi,psiddot,theta,thetadot,thetaddot)
%alphaP
%    ALPHA_BODY = alphaP(PHIDOT,PHIDDOT,PSIDOT,PSI,PSIDDOT,THETA,THETADOT,THETADDOT)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    19-Jul-2025 03:33:54

t2 = cos(psi);
t3 = cos(theta);
t4 = sin(psi);
t5 = sin(theta);
alpha_body = [psidot.*(t2.*thetadot-phidot.*t3.*t4)+t4.*thetaddot+phiddot.*t2.*t3-phidot.*t2.*t5.*thetadot;-psidot.*(t4.*thetadot+phidot.*t2.*t3)+t2.*thetaddot-phiddot.*t3.*t4+phidot.*t4.*t5.*thetadot;psiddot+phiddot.*t5+phidot.*t3.*thetadot];
end
