%--- symbolic once, in its own short script ---
syms phi theta psi phidot thetadot psidot phiddot thetaddot psiddot real

Rx = [1,0,0; 0,cos(phi),-sin(phi); 0,sin(phi),cos(phi)];
Ry = [cos(theta),0,sin(theta); 0,1,0; -sin(theta),0,cos(theta)];
Rz = [cos(psi),-sin(psi),0; sin(psi),cos(psi),0; 0,0,1];
R  = Rx*Ry*Rz;

Rdot = diff(R,phi)*phidot ...
     + diff(R,theta)*thetadot ...
     + diff(R,psi)*psidot;

S     = simplify(R.'*Rdot);        % skew(ω)
Sdot  = simplify( ...
           diff(S,phi)*phidot   + ...
           diff(S,theta)*thetadot + ...
           diff(S,psi)*psidot  + ...
           diff(S,phidot)*phiddot + ...
           diff(S,thetadot)*thetaddot + ...
           diff(S,psidot)*psiddot );

alpha_body = [ Sdot(3,2); Sdot(1,3); Sdot(2,1) ]

% % turn it into a tiny numeric function:
% alpha_fun = matlabFunction(alpha_body,);
